In [1]:
import numpy as np
# Basic Array Creation

In [2]:
# // Array creation
arr = np.array([12,34,65,34,78,21])
arr

array([12, 34, 65, 34, 78, 21])

In [3]:
# // List to array like matrix form
l = [[12,43,54,35,76,67]]
np.array(l)

array([[12, 43, 54, 35, 76, 67]])

In [4]:
#// Make array sing arange method(starting : ending : steps)
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [5]:
#// Zerose inside array like matrix 
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
#// Linespace -> Defines no of elements in a range from starting to end (starting : endpoint : no. of elements inside the range)
arr = np.linspace(0,50,30)
arr

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [7]:
import random #// This module is used to generate random numbers.

In [8]:
arr = np.random.rand(10) #// Normalization (gives numbers between 1 and 0)
arr

array([0.14234729, 0.22090855, 0.67896881, 0.48733234, 0.77276603,
       0.70929135, 0.57760084, 0.91648343, 0.3070553 , 0.61853947])

In [9]:
arr = np.random.randn(10) #// Gives numbers between -3 and 3)
arr

array([ 1.73401554,  0.89770267, -1.59833067, -0.03339912,  0.18192996,
       -0.88527368,  0.12831531, -0.81971362, -0.46516943,  0.08497895])

In [10]:
arr = np.random.randint(10,20,10) #// gives random numbers in a range randomly everytime. (starting : ending : no. of elements)
arr

array([15, 17, 10, 16, 11, 15, 18, 15, 18, 18], dtype=int32)

In [11]:
#//Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #// Array like matrix
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr.shape #// Gives shape of the matrix (order of matrix)

(4, 3)

In [13]:
arr.size #// Gives the size -> no of elements inside the matrix

12

In [14]:
arr.dtype #// Gives the datatype

dtype('int64')

In [15]:
#// Array Methods
arr.min() #// Gives the smallest number in the array of matrix

np.int64(1)

In [16]:
arr.max() #// Gives the largest number inside an array of matrix

np.int64(12)

In [17]:
arr.sum() #// Gives the sum of elements inside the array of matrix

np.int64(78)

In [18]:
np.sum(arr,axis=0) #// Gives sum of elements in a column(vertical)

array([22, 26, 30])

In [19]:
np.sum(arr,axis=1) #// Gives sum of elements in a row(horizontal)

array([ 6, 15, 24, 33])

In [20]:
arr.std() # To find standard deviation

np.float64(3.452052529534663)

In [21]:
arr.argmax() #// Maximun index

np.int64(11)

In [22]:
arr.argmin() #// Minimum index

np.int64(0)

In [23]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [24]:
arr.reshape(6,5)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [25]:
# NuPy Indexing and Slicing of Vectors
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
arr[35] #// Array Indexing

np.int64(45)

In [27]:
arr[2:5] #// Array Slicing -> [Position of starting : ending ]

array([12, 13, 14])

In [28]:
arr[1:35:2] #// Array Slicing In between anywhere -> [From where to start : till where to go : Steps to take]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43])

In [29]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
arr[2,4]

np.int64(15)

In [31]:
arr[1:4,4:5]

array([[10],
       [15],
       [20]])

In [32]:
arr[0:3,2:5] #// [Starting index no of row : no of row till where it go , starting index no of column : no of row till where it go ]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [33]:
#//Boolean Indexing 
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
boolen_Index = arr % 2 == 0
arr = arr[boolen_Index]
arr

array([12, 14, 16, 18, 20])

In [35]:
# Broadcasting
l = [12,32,45,65,24,19]
arr = np.array(l)
arr

array([12, 32, 45, 65, 24, 19])

In [36]:
arr + 20 #//Breadcasting the array

array([32, 52, 65, 85, 44, 39])

In [41]:
#// Advanced Array Manipulation
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([11,12,13,14,15,16,17,18,19,20])
arr = np.vstack((a,b)) #// Vertical Stacking of Arrays
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [42]:
arr2 = np.hstack((a,b)) #//Horizontal Stacking of Array
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
arr3 = np.column_stack((a,b))
arr3

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

In [55]:
C = arr #// First need to put the array inside a container before splitting
arr4 = np.hsplit(C,2) #//Horizontal Splitting
arr4

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]),
 array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]])]

In [56]:
arr4 = np.vsplit(C,2) #//Vertical Splitting
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])