In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
MyList =[[1,2,3],[4,5,6],[7,8,9]]
np.array(MyList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arrayRange = np.arange(1,40,2)
arrayRange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [8]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.linspace(1,100,50)
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [11]:
np.random.rand(10)

array([0.86393923, 0.31391973, 0.32418829, 0.65968943, 0.80568218,
       0.74948244, 0.32971359, 0.98359773, 0.77274909, 0.22638445])

In [14]:
np.random.randn(10)

array([-0.61504456, -0.64451705,  0.37797444,  1.34884997, -0.97723169,
        0.69643989, -0.26215776,  1.62040753,  0.22315321, -1.56108699])

In [15]:
np.random.randint(10,20,10)

array([17, 13, 17, 10, 12, 15, 13, 13, 19, 19])

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])