In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
MyList =[[1,2,3],[4,5,6],[7,8,9]]
np.array(MyList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arrayRange = np.arange(1,40,2)
arrayRange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [9]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.linspace(1,100,50)
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [11]:
np.random.rand(10)

array([0.46259133, 0.20665155, 0.6985537 , 0.2419002 , 0.38615079,
       0.94693124, 0.44617599, 0.09777453, 0.62760008, 0.86551922])

In [12]:
np.random.randn(10)

array([ 0.95485477, -0.42578537,  1.26617285, -0.31679335,  0.37105229,
        0.28656865,  0.23765503, -0.20451395, -0.60696902,  0.33477719])

In [13]:
np.random.randint(10,20,10)

array([10, 15, 16, 15, 16, 18, 11, 11, 17, 11])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.max()

np.int64(9)

In [20]:
arr.sum()

np.int64(45)

In [21]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [24]:
arr.argmax()

np.int64(8)

In [25]:
arr.argmin()

np.int64(0)

In [28]:
arr3 = np.arange(1,31)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr3 =arr3.reshape(6,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
arr4 = np.arange(11,21)
arr4

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
arr4[3]

np.int64(14)

In [51]:
arr3[2,3]

np.int64(14)