In [79]:
import numpy as np
import random as rd

In [80]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [81]:
l = [[1,2,3], [4,5,6], [7,8,9]]
arr2 = np.array(l)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr = np.arange(1,50,5)
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [83]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.random.rand(45)

array([0.28578425, 0.81274751, 0.33635146, 0.37343004, 0.69028792,
       0.41660258, 0.55649048, 0.20299492, 0.68215317, 0.12380421,
       0.58605603, 0.24814244, 0.59597376, 0.41337319, 0.87921962,
       0.31184517, 0.50940037, 0.15509177, 0.54440306, 0.30578407,
       0.50642403, 0.38067089, 0.84022322, 0.11663571, 0.41066024,
       0.8193342 , 0.99812673, 0.13774096, 0.17759028, 0.0189259 ,
       0.67880353, 0.94808473, 0.23683381, 0.81717457, 0.50082339,
       0.89129799, 0.01256404, 0.45059579, 0.54454117, 0.72468533,
       0.66540827, 0.83767233, 0.08950809, 0.40927283, 0.86874174])

In [86]:
np.random.randn(45)

array([-0.08651295, -0.8114584 , -1.58043934,  0.76256749, -0.16667079,
        0.05631492, -0.35019355,  0.67365316, -0.07777089,  1.08374957,
       -0.90869593, -0.88691902,  0.73465746,  0.93971465, -1.27304118,
        0.75889889, -0.35217106, -0.13092671, -0.41708245, -0.07346521,
        2.44963294, -0.82870056, -0.13744044,  0.00559856, -3.25698456,
       -0.44279828, -0.22572927,  0.52661895,  2.42107238, -1.59926913,
       -0.67252429,  1.01732015, -0.45758725, -0.57924419, -0.92960674,
        0.15155053,  0.19067042, -0.49737613,  1.07338644, -0.45169814,
        0.17747408,  0.86076035,  0.34869401, -1.43571106, -0.12038841])

In [87]:
np.random.randint(1, 100, 45)

array([94, 42, 68, 47, 37, 81, 76, 21, 93, 15, 35, 23, 89, 18, 65, 55, 74,
       36, 92, 63, 28, 74, 85, 24, 56, 55, 67, 27, 66, 91, 15, 13, 66, 84,
       83, 21, 17, 30, 97, 51,  1, 64, 46, 49, 25], dtype=int32)

In [88]:
arr2.shape  # Output the shape of the array

(3, 3)

In [89]:
arr.size

12

In [90]:
arr2.min()  # Minimum value in the array

np.int64(1)

In [91]:
arr2.max()  # Maximum value in the array

np.int64(9)

In [92]:
arr.sum()  # Sum of all elements in the array

np.float64(12.0)

In [93]:

arr3 = np.arange(1,41)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [94]:
arr3 =  arr3.reshape(8,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [95]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [96]:
arr[4]

np.int64(5)

In [97]:
arr[1:4]

array([2, 3, 4])

In [98]:
arr[0::2]

array([1, 3, 5])

In [99]:
arr = np.arange(1,52)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

In [106]:
arr = arr.reshape(3,17)  # Reshape the array to 13 rows and 4 columns
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34],
       [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51]])

In [ ]:
arr[1:3, 5:11]  # Slicing rows 1 to 2 and columns 5 to 10

In [107]:
arr.ndim  # Returns the number of dimensions (should be 2 for a 2D array)  # Slicing the array to get elements from index 5 to 10 in the first dimension and index 1 to 2 in the second dimension

2

In [114]:
arr[1:2, 5:10]  # Slicing rows 1 to 2 and columns 5 to 10

array([[23, 24, 25, 26, 27]])

In [ ]:
arr[0:3,6:16] # Jaha sain cahiye uska indx or jaha tak cahiye usse + 1 wala index lagana hain both row and column

array([[ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])