In [1]:
import numpy as np

In [2]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [8]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[2]

array([11, 12, 13, 14, 15])

In [14]:
arr[1:5]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
arr[3:5:1]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
# arr[:, 1:4]
arr[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [89]:
ArrBoolean = np.arange(11,23)
ArrBoolean

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [93]:
boolean_index = ArrBoolean % 2 == 0
ArrBoolean = ArrBoolean[boolean_index]
ArrBoolean

array([12, 14, 16, 18, 20, 22])

In [102]:
l = [10,20,30,40,50,60]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50, 60, 70])

In [103]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [105]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [111]:
np.hstack((a,b))
np.hsplit()

TypeError: hsplit() missing 2 required positional arguments: 'ary' and 'indices_or_sections'